/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author Germo
 */
public class Circular extends javax.swing.JFrame {

    /**
     * Creates new form JF
     */
    public Circular() {
        initComponents();
        getContentPane().setBackground(new Color(213,233,255));
        tfield1.setBackground(new Color(218,218,218));
        tfield2.setBackground(new Color(218,218,218));
        tfield3.setBackground(new Color(218,218,218));
        this.setLocationRelativeTo(null);
        this.setTitle(" Gráfico circular ");
    }

    boolean bandera = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        tfield3 = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        tfield1 = new javax.swing.JTextField();
        tfield2 = new javax.swing.JTextField();
        boton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Violeta:");

        tfield3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfield3ActionPerformed(evt);
            }
        });

        label2.setText("Rojo:");

        label3.setText("Azul: ");

        tfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfield1ActionPerformed(evt);
            }
        });

        tfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfield2ActionPerformed(evt);
            }
        });

        boton1.setText("Graficar");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton1)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(label2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(label1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(tfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(tfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton1)
                    .addComponent(label3)
                    .addComponent(tfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfield3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfield3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfield3ActionPerformed

    private void tfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfield1ActionPerformed

    private void tfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfield2ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed

        bandera = true;
        repaint();

    }//GEN-LAST:event_boton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Circular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Circular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Circular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Circular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Circular().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JTextField tfield1;
    private javax.swing.JTextField tfield2;
    private javax.swing.JTextField tfield3;
    // End of variables declaration//GEN-END:variables

    @Override

    public void paint(Graphics g) {

        try {

            super.paint(g);

            if (bandera == true) {

                String SVioleta = tfield1.getText();
                String SRojo = tfield2.getText();
                String SCeleste = tfield3.getText();

                int IVioleta = Integer.parseInt(SVioleta);
                int IRojo = Integer.parseInt(SRojo);
                int ICeleste = Integer.parseInt(SCeleste);

                int total = IVioleta + IRojo + ICeleste;

                float FVioleta = IVioleta;
                float FRojo = IRojo;
                float FCeleste = ICeleste;
                float Ftotal = total;

                double DGVioleta = (FVioleta * 360) / Ftotal;
                int GVioleta = (int) Math.ceil(DGVioleta);

                double DGRojo = (FRojo * 360) / Ftotal;
                int GRojo = (int) Math.ceil(DGRojo);

                double DGCeleste = (FCeleste * 360) / Ftotal;
                int GCeleste = (int) Math.ceil(DGCeleste);

                float PVioleta = (FVioleta * 100) / Ftotal;
                float PRojo = (FRojo * 100) / Ftotal;
                float PCeleste = (FCeleste * 100) / Ftotal;

                g.setColor(new Color(92, 84, 169));
                g.fillArc(40, 80, 200, 200, 0, GVioleta);
                g.fillRect(270, 120, 20, 20);
                g.drawString(" Color Violeta  %" + (double) Math.round(PVioleta * 10) / 10, 300, 140);

                g.setColor(new Color(243, 79, 63));
                g.fillArc(40, 80, 200, 200, GVioleta, GRojo);
                g.fillRect(270, 170, 20, 20);
                g.drawString(" Color Rojo  %" + (double) Math.round(PRojo * 10) / 10, 300, 190);

                g.setColor(new Color(0, 235, 210));
                g.fillArc(40, 80, 200, 200, GVioleta + GRojo, GCeleste);
                g.fillRect(270, 220, 20, 20);
                g.drawString(" Color Celeste  %" + (double) Math.round(PCeleste * 10) / 10, 300, 240);

            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, " Debe rellenar los campos correctamente para continuar", " Error ", JOptionPane.WARNING_MESSAGE);

        }
    }
}
